apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.services.http.name" . }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.http.type }}
  ports:
  - name: http
    port: {{ .Values.services.http.port }}
    targetPort: http
    {{- with .Values.services.http.nodePort }}
    nodePort: {{ . }}
    {{- end }}
    protocol: TCP
  selector:
    {{- include "nginx.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.services.stream.name" . }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.gitlab_ssh.type }}
  ports:
  - name: gitlab-ssh
    port: {{ .Values.services.gitlab_ssh.port }}
    targetPort: gitlab-ssh
    {{- with .Values.services.gitlab_ssh.nodePort }}
    nodePort: {{ . }}
    {{- end }}
    protocol: TCP
  selector:
    {{- include "nginx.selectorLabels" . | nindent 4 }}
