apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "min-auth.fullname" . }}
  labels:
    {{- include "min-auth.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "min-auth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "min-auth.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        env:
        - name: RUST_LOG
          value: "{{ .Values.rust.log }}"
        - name: REDIS_URI
          value: "{{ .Values.redis.uri }}"
        - name: REDIS_LIFETIME
          value: "{{ .Values.redis.lifetime }}"
        - name: MYSQL_HOST
          value: "{{ .Values.mysql.host }}"
        - name: MYSQL_PORT
          value: "{{ .Values.mysql.port }}"
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.mysql.user.secretName }}"
              key: "{{ .Values.mysql.user.keys.username }}"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.mysql.user.secretName }}"
              key: "{{ .Values.mysql.user.keys.password }}"
        - name: MYSQL_DBNAME
          value: "{{ .Values.mysql.dbname }}"
        - name: PASSWORD_SECRET
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.passwordSecret.secretName }}"
              key: "{{ .Values.passwordSecret.key }}"
