apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openldap.fullname" . }}
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "openldap.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "openldap.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: ldap
          containerPort: 389
          protocol: TCP
        - name: ldaps
          containerPort: 636
          protocol: TCP
        env:
        - name: "LDAP_DOMAIN"
          value: "{{ .Values.domain }}"
        - name: "LDAP_ADMIN_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.admin.password.secretName }}
              key: {{ .Values.admin.password.key }}
