apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mysql.storages.data.name" . }}
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: {{ .Values.storages.data.mode | quote }}
  resources:
    requests:
      storage: {{ .Values.storages.data.size | quote }}
  storageClassName: {{ include "mysql.storages.data.name" . }}
