apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mysql.storages.data.name" . }}
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: "{{ .Values.storages.data.size }}"
  storageClassName: {{ include "mysql.storages.data.name" . }}
