apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "nginx.storages.config.name" . }}
spec:
  capacity:
    storage: {{ .Values.storages.config.size | quote }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ include "nginx.storages.config.name" . }}
  local:
    path: {{ .Values.storages.config.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.storages.config.hostname }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "nginx.storages.crl.name" . }}
spec:
  capacity:
    storage: {{ .Values.storages.crl.size | quote }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ include "nginx.storages.crl.name" . }}
  local:
    path: {{ .Values.storages.crl.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.storages.crl.hostname }}
