apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress.storages.html.name" . }}
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.storages.html.size | quote }}
  storageClassName: {{ include "wordpress.storages.html.name" . }}
