apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "web-server.storages.config.name" . }}
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.storages.config.size | quote }}
  storageClassName: {{ include "web-server.storages.config.name" . }}
