apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "redmine.storages.files.name" . }}
spec:
  capacity:
    storage: {{ .Values.storages.files.size | quote }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ include "redmine.storages.files.name" . }}
  local:
    path: {{ .Values.storages.files.path | quote }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.storages.files.hostname | quote }}
