apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "redmine.storages.files.name" . }}
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.storages.files.size | quote }}
  storageClassName: {{ include "redmine.storages.files.name" . }}
